"""
AI Data Agent — Multi-Agent System for Databricks Model Serving.

ARCHITECTURE (mirrors the tutorial transcript):
  ┌───────────────────────────────────────────────────────┐
  │                   DATA AGENT (Parent)                  │
  │                  ┌──── AI-DECIDE ────┐                 │
  │                  │    Router Node    │                 │
  │                  └──┬────┬────┬────┘                 │
  │             SQL      │    │    │  KNOWLEDGE            │
  │              ┌───────┘    │    └────────┐              │
  │     SQL ANALYST    ETL ANALYST   KNOWLEDGE SEARCH      │
  │    (Stateful)      (ReAct Loop)   (Vector Search)     │
  │  Curate→Context   Reason→Act→     Search PDF docs    │
  │  →Generate→Judge   Reason→Act       Return results    │
  │  →Execute→Format                                        │
  └───────────────────────────────────────────────────────┘

Key Concepts Demonstrated:
  • Stateful Orchestration (Pydantic models, LangGraph state)
  • ReAct Architecture (Reason + Act loops)
  • Context Engineering (schema introspection, dynamic context)
  • AI-as-Judge (structured output for SQL safety check)
  • LLM Routing (low/medium/high models per task complexity)
  • Sub-Agent coordination (parent routes to specialized agents)
  • UC Functions as agent tools (Unity Catalog function toolkit)
  • Model Serving deployment (ResponsesAgent pattern)
"""
import os
import json
import logging
from typing import Annotated, Generator, Literal, Sequence
from operator import add

import mlflow
from mlflow.pyfunc import ResponsesAgent
from mlflow.types.responses import (
    ResponsesAgentRequest,
    ResponsesAgentResponse,
    ResponsesAgentStreamEvent,
    output_to_responses_items_stream,
    to_chat_completions_input,
)

from pydantic import BaseModel, Field
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, ToolMessage
from langchain_core.runnables import RunnableLambda
from langgraph.graph import END, StateGraph
try:
    from langgraph.graph import START
except ImportError:
    START = "__start__"
from langgraph.prebuilt.tool_node import ToolNode

logger = logging.getLogger(__name__)

# ════════════════════════════════════════════════════════════════
# CONFIGURATION — Foundation Model API endpoints (Databricks-native)
# ════════════════════════════════════════════════════════════════
LLM_HIGH = os.environ.get("LLM_HIGH", "databricks-claude-sonnet-4-6")
LLM_MEDIUM = os.environ.get("LLM_MEDIUM", "databricks-gpt-5-mini")
LLM_LOW = os.environ.get("LLM_LOW", "databricks-gpt-5-nano")
CATALOG = os.environ.get("CATALOG", "ai_agent_demo")
SCHEMA = os.environ.get("SCHEMA", "customer_support")

# ════════════════════════════════════════════════════════════════
# PYDANTIC STATE MODELS — Stateful orchestration backbone
# ════════════════════════════════════════════════════════════════

class SQLAgentState(BaseModel):
    """State carried through every node of the SQL Analyst stateful graph.

    Each node reads from and writes to this state, maintaining context
    across the entire pipeline without losing intermediate results.
    """
    messages: list = Field(default_factory=list,
        description="Chat messages processed by the SQL agent")
    user_question: str = Field(default="", description="Raw user input")
    curated_question: str = Field(default="", description="Refined user question")
    prompt_context: str = Field(default="", description="Prompt with DB schema context")
    generated_sql: str = Field(default="", description="SQL generated by LLM")
    is_safe: Literal["yes", "no"] = Field(default="no", description="Safety flag from AI judge")
    judge_comments: str = Field(default="", description="Judge feedback")
    sql_result: str = Field(default="", description="SQL execution result")
    final_answer: str = Field(default="", description="User-facing answer")


class JudgeSchema(BaseModel):
    """Structured output schema for the AI-as-judge SQL safety check."""
    answer: Literal["yes", "no"] = Field(description="Whether the SQL query is safe to execute")
    comments: str = Field(default="", description="Feedback from the judge")


class RouterSchema(BaseModel):
    """Structured output schema for the AI-decide router."""
    answer: Literal["SQL", "ETL", "KNOWLEDGE"] = Field(
        description="Route: SQL for data queries, ETL for extract/transform/load, KNOWLEDGE for product docs")
    comments: str = Field(default="", description="Brief justification for routing")


class ETLAgentState(BaseModel):
    """State for the ETL Analyst ReAct loop."""
    messages: Annotated[list, add] = Field(default_factory=list,
        description="Chat messages for the ETL agent")


class KnowledgeAgentState(BaseModel):
    """State for the Knowledge Search agent."""
    messages: Annotated[list, add] = Field(default_factory=list,
        description="Chat messages for the knowledge agent")
    search_results: str = Field(default="", description="Product documentation search results")
    final_answer: str = Field(default="", description="User-facing answer")


class DataAgentState(BaseModel):
    """State for the parent Data Agent orchestrator."""
    messages: Annotated[list, add] = Field(default_factory=list,
        description="Chat messages for the parent agent")
    route: str = Field(default="", description="Routing decision: SQL, ETL, or KNOWLEDGE")
    final_answer: str = Field(default="", description="Final user-facing answer")


# ════════════════════════════════════════════════════════════════
# LLM PICKER — Route to the right model for the right task
# Low-end for curation/formatting, Medium for SQL/code,
# High-end for complex reasoning and routing decisions.
# ════════════════════════════════════════════════════════════════

def message_text(message):
    content = message.content
    if isinstance(content, str):
        return content
    return "\n".join(block.get("text", "") for block in content
                     if isinstance(block, dict) and block.get("type") in ("text", "output_text"))


def pick_llm(level: str = "low"):
    """Return a ChatDatabricks instance based on task complexity.

    This demonstrates LLM ROUTING — using cheaper models for simple tasks
    (question curation, response formatting) and more capable models for
    complex tasks (SQL generation, routing decisions) to optimize cost.
    """
    from databricks_langchain import ChatDatabricks
    level = level.lower().strip()
    if level == "low":
        return ChatDatabricks(endpoint=LLM_LOW, temperature=0)
    elif level == "medium":
        return ChatDatabricks(endpoint=LLM_MEDIUM, temperature=0)
    elif level == "high":
        return ChatDatabricks(endpoint=LLM_HIGH, temperature=0)
    else:
        return ChatDatabricks(endpoint=LLM_LOW, temperature=0)


# ════════════════════════════════════════════════════════════════
# UC FUNCTION TOOLS — Databricks Unity Catalog functions as agent tools
# These are SQL functions registered in UC that the agent can call.
# ════════════════════════════════════════════════════════════════

def _execute_sql_sdk(sql: str) -> str:
    """Execute SQL via Databricks SDK statement_execution API.

    Works in BOTH notebook context AND Model Serving (no SparkSession needed).
    Uses the workspace SQL warehouse to execute the query.
    """
    from databricks.sdk import WorkspaceClient
    w = WorkspaceClient()
    try:
        from .runtime import execute_statement
    except ImportError:
        from runtime import execute_statement
    return execute_statement(w, sql)


def _get_uc_tools():
    """Load UC Function tools for the ETL and Knowledge agents."""
    from langchain_core.tools import tool

    @tool
    def search_product_docs(query: str) -> str:
        """Search product PDF documentation and return source filenames and content."""
        escaped = query.replace("'", "''")
        return _execute_sql_sdk(f"SELECT {CATALOG}.{SCHEMA}.search_product_docs('{escaped}') AS documentation")

    return [search_product_docs]


# ════════════════════════════════════════════════════════════════
# SQL ANALYST SUB-AGENT — Stateful LangGraph
# Nodes: curate → context → generate → judge → [execute | cancel] → format
# Demonstrates: stateful orchestration, context engineering, AI-as-judge
# ════════════════════════════════════════════════════════════════

def _curate_question(state: SQLAgentState) -> SQLAgentState:
    """Node 1: Curate the user's raw question into a clear, structured query."""
    llm = pick_llm("low")  # Low-end LLM — simple text curation
    prompt = f"Curate the following question so that it is clear, specific, and well-structured. Output only the curated question, nothing else:\n\n{state.user_question}"
    response = llm.invoke(prompt)
    state.curated_question = message_text(response)
    state.messages = state.messages + [HumanMessage(content=message_text(response))]
    return state


def _add_context(state: SQLAgentState) -> SQLAgentState:
    """Node 2: Add database schema context to the curated question.

    CONTEXT ENGINEERING: Call the get_schema_info UC function to get table
    names, column types so the LLM can generate syntactically correct SQL.
    """
    schema_info = _execute_sql_sdk(f"SELECT {CATALOG}.{SCHEMA}.get_schema_info()")
    if "Error" in schema_info:
        schema_info = f"Tables: {CATALOG}.{SCHEMA}.cust_service_data, {CATALOG}.{SCHEMA}.policies"

    prompt = f"""You are a SQL analyst agent. Convert the user's question into a valid Databricks SQL query.

User question: {state.curated_question}

Database schema details (Delta tables in Unity Catalog):
{schema_info}

Rules:
- Generate ONLY the SQL query without any explanation.
- Always LIMIT output to 10 rows unless user asks for more.
- Use the exact table and column names from the schema above.
- Tables are in {CATALOG}.{SCHEMA} catalog.schema — use fully qualified names.

SQL query:"""
    state.prompt_context = prompt
    return state


def _generate_sql(state: SQLAgentState) -> SQLAgentState:
    """Node 3: Generate SQL using a medium-end LLM with full context."""
    llm = pick_llm("medium")  # Medium LLM — code/SQL generation needs accuracy
    response = llm.invoke(state.prompt_context)
    state.generated_sql = message_text(response).strip()
    if state.generated_sql.startswith("```sql"):
        state.generated_sql = state.generated_sql[6:]
    if state.generated_sql.startswith("```"):
        state.generated_sql = state.generated_sql[3:]
    if state.generated_sql.endswith("```"):
        state.generated_sql = state.generated_sql[:-3]
    state.generated_sql = state.generated_sql.strip()
    return state


def _is_safe_sql(state: SQLAgentState) -> SQLAgentState:
    """Node 4: AI-as-Judge — check if the generated SQL is safe to execute.

    Uses structured output (Pydantic schema) to force the LLM to return
    a yes/no verdict with justification. This is a guardrail against
    SQL injection and destructive queries.
    """
    try:
        from .runtime import validate_sql
    except ImportError:
        from runtime import validate_sql
    try:
        validate_sql(state.generated_sql)
    except ValueError as exc:
        state.is_safe = "no"
        state.judge_comments = str(exc)
        return state
    llm = pick_llm("low")
    llm_judge = llm.with_structured_output(JudgeSchema)
    judge_prompt = f"""You are a SQL judge for data security. Determine whether the SQL query is safe to execute.

The SQL query should ONLY be used for data retrieval (SELECT) and should NOT modify the database.
Reject any INSERT, UPDATE, DELETE, DROP, TRUNCATE, ALTER, or other DDL/DML commands.

SQL query to validate:
{state.generated_sql}"""
    response = llm_judge.invoke(judge_prompt)
    result = response.model_dump() if hasattr(response, 'model_dump') else {"answer": "no", "comments": str(response)}
    state.is_safe = result.get("answer", "no")
    state.judge_comments = result.get("comments", "")
    return state


def _execute_sql(state: SQLAgentState) -> SQLAgentState:
    """Node 5a: Execute the safe SQL query via Databricks SDK (works in Model Serving)."""
    state.sql_result = _execute_sql_sdk(state.generated_sql)
    return state


def _cancel_sql(state: SQLAgentState) -> SQLAgentState:
    """Node 5b: Cancel execution — query was deemed unsafe."""
    state.final_answer = f"⚠️ The generated SQL query was deemed unsafe to execute.\n\nReason: {state.judge_comments}\n\nGenerated query: {state.generated_sql}"
    state.messages = state.messages + [AIMessage(content=state.final_answer)]
    return state


def _format_answer(state: SQLAgentState) -> SQLAgentState:
    """Node 6: Format the execution results into a user-friendly response."""
    llm = pick_llm("low")  # Low-end LLM — simple summarization
    prompt = f"""You are a SQL analyst. Provide the final answer based on the execution result.
The answer should be concise, clear, and address the user's question.
Do NOT include SQL code in the answer.

User's original question: {state.curated_question}

Execution result:
{state.sql_result}"""
    response = llm.invoke(prompt)
    state.final_answer = message_text(response)
    state.messages = state.messages + [AIMessage(content=state.final_answer)]
    return state


def _safety_edge(state: SQLAgentState) -> str:
    """Conditional edge: route based on the AI judge's safety verdict."""
    if state.is_safe.lower() == "yes":
        return "execute_sql"
    return "cancel_sql"


def _build_sql_analyst_graph():
    """Build and compile the SQL Analyst stateful graph.

    Graph flow:
      START → curate_question → add_context → generate_sql → is_safe_sql
        → [yes] → execute_sql → format_answer → END
        → [no]  → cancel_sql → END
    """
    graph = StateGraph(SQLAgentState)
    graph.add_node("curate_question", RunnableLambda(_curate_question))
    graph.add_node("add_context", RunnableLambda(_add_context))
    graph.add_node("generate_sql", RunnableLambda(_generate_sql))
    graph.add_node("is_safe_sql", RunnableLambda(_is_safe_sql))
    graph.add_node("execute_sql", RunnableLambda(_execute_sql))
    graph.add_node("cancel_sql", RunnableLambda(_cancel_sql))
    graph.add_node("format_answer", RunnableLambda(_format_answer))

    graph.add_edge(START, "curate_question")
    graph.add_edge("curate_question", "add_context")
    graph.add_edge("add_context", "generate_sql")
    graph.add_edge("generate_sql", "is_safe_sql")
    graph.add_conditional_edges("is_safe_sql", _safety_edge,
        {"execute_sql": "execute_sql", "cancel_sql": "cancel_sql"})
    graph.add_edge("execute_sql", "format_answer")
    graph.add_edge("cancel_sql", END)
    graph.add_edge("format_answer", END)
    return graph.compile()


# ════════════════════════════════════════════════════════════════
# ETL ANALYST SUB-AGENT — ReAct Loop (Reasoning + Acting)
# Uses UC Function tools in a tool-calling loop.
# Demonstrates: ReAct architecture, tool calling, react loops
# ════════════════════════════════════════════════════════════════

def _build_etl_analyst_graph():
    """Build and compile the ETL Analyst ReAct agent.

    Graph flow (ReAct loop):
      START → llm_node ↔ tool_node
        → [has tool calls] → tool_node → llm_node (loop)
        → [no tool calls]  → END
    """
    try:
        from .runtime import etl_tools
    except ImportError:
        from runtime import etl_tools
    tools = etl_tools()
    llm = pick_llm("high")  # High-end LLM for agentic tool-calling loops

    if tools:
        llm_with_tools = llm.bind_tools(tools)
    else:
        llm_with_tools = llm

    system_prompt = (
        "You are a Python data analyst ETL agent. You have access to tools for "
        "extracting allowlisted HTTPS JSON APIs, inspecting datasets, and applying declarative transformations. "
        "When the user asks to extract, transform, load, or analyze data, "
        "use the appropriate tools. If the task is complete, provide a direct answer."
    )

    def _etl_llm_node(state: ETLAgentState) -> dict:
        messages = [SystemMessage(content=system_prompt)] + state.messages
        response = llm_with_tools.invoke(messages)
        return {"messages": [response]}

    def _should_continue(state: ETLAgentState) -> str:
        last = state.messages[-1] if state.messages else None
        if isinstance(last, AIMessage) and getattr(last, "tool_calls", None):
            return "tool_node"
        return END

    graph = StateGraph(ETLAgentState)
    graph.add_node("llm_node", RunnableLambda(_etl_llm_node))

    if tools:
        graph.add_node("tool_node", ToolNode(tools))
        graph.add_edge(START, "llm_node")
        graph.add_conditional_edges("llm_node", _should_continue,
            {"tool_node": "tool_node", END: END})
        graph.add_edge("tool_node", "llm_node")
    else:
        graph.add_edge(START, "llm_node")
        graph.add_edge("llm_node", END)

    return graph.compile()


# ════════════════════════════════════════════════════════════════
# KNOWLEDGE SEARCH SUB-AGENT — Search parsed PDF product docs
# Uses UC function search_product_docs to find relevant docs.
# ════════════════════════════════════════════════════════════════

def _build_knowledge_search_graph():
    """Build the Knowledge Search agent that queries parsed PDF documentation."""
    tools = _get_uc_tools()
    llm = pick_llm("medium")

    system_prompt = (
        "You are a knowledge search agent for customer support. You have access to "
        "product documentation stored in Databricks. Use the search_product_docs tool "
        "to find relevant product information and answer the user's question. "
        "If no relevant documentation is found, say so clearly. Cite the document filenames returned by the tool."
    )

    knowledge_tools = [t for t in tools if "search_product_docs" in getattr(t, "name", "")]
    if knowledge_tools:
        llm_with_tools = llm.bind_tools(knowledge_tools)
    else:
        llm_with_tools = llm

    def _knowledge_llm_node(state: KnowledgeAgentState) -> dict:
        messages = [SystemMessage(content=system_prompt)] + state.messages
        response = llm_with_tools.invoke(messages)
        return {"messages": [response]}

    def _should_continue_knowledge(state: KnowledgeAgentState) -> str:
        last = state.messages[-1] if state.messages else None
        if isinstance(last, AIMessage) and getattr(last, "tool_calls", None):
            return "tool_node"
        return END

    graph = StateGraph(KnowledgeAgentState)
    graph.add_node("llm_node", RunnableLambda(_knowledge_llm_node))

    if knowledge_tools:
        graph.add_node("tool_node", ToolNode(knowledge_tools))
        graph.add_edge(START, "llm_node")
        graph.add_conditional_edges("llm_node", _should_continue_knowledge,
            {"tool_node": "tool_node", END: END})
        graph.add_edge("tool_node", "llm_node")
    else:
        graph.add_edge(START, "llm_node")
        graph.add_edge("llm_node", END)

    return graph.compile()


# ════════════════════════════════════════════════════════════════
# AI-DECIDE ROUTER — Parent Data Agent with intelligent routing
# Demonstrates: sub-agent coordination, LLM routing with structured output
# ════════════════════════════════════════════════════════════════

def _build_data_agent_graph():
    """Build the parent Data Agent that routes to sub-agents.

    Graph flow:
      START → router_node
        → [SQL]      → sql_node      → END
        → [ETL]      → etl_node      → END
        → [KNOWLEDGE] → knowledge_node → END
    """
    llm = pick_llm("high")  # High-end LLM for accurate routing decisions
    llm_router = llm.with_structured_output(RouterSchema)

    sql_analyst = _build_sql_analyst_graph()
    etl_analyst = _build_etl_analyst_graph()
    knowledge_agent = _build_knowledge_search_graph()

    def _router_node(state: DataAgentState) -> dict:
        """AI-DECIDE: Classify the user query and route to the right sub-agent."""
        message = state.messages[-1].content if state.messages else ""
        router_prompt = f"""You are a router for a multi-agent data system. Classify the user's question:

- Answer 'SQL' for data retrieval, analytics, aggregations, or queries about customer service data, policies, or products.
- Answer 'ETL' for extracting, transforming, loading, or fetching data from external sources.
- Answer 'KNOWLEDGE' for questions about product documentation, specs, features, or manuals.

User question: {message}"""
        response = llm_router.invoke(router_prompt)
        result = response.model_dump() if hasattr(response, 'model_dump') else {"answer": "SQL"}
        return {"route": result.get("answer", "SQL")}

    def _sql_node(state: DataAgentState) -> dict:
        """Invoke the SQL Analyst sub-agent."""
        message = "\n".join(f"{m.type}: {m.content}" for m in state.messages)
        sql_input = SQLAgentState(messages=[], user_question=message)
        result = sql_analyst.invoke(sql_input)
        final = result["final_answer"]
        return {"final_answer": final, "messages": [AIMessage(content=final)]}

    def _etl_node(state: DataAgentState) -> dict:
        """Invoke the ETL Analyst sub-agent (ReAct loop)."""
        message = state.messages[-1].content if state.messages else ""
        etl_input = ETLAgentState(messages=[HumanMessage(content=message)])
        result = etl_analyst.invoke({"messages": state.messages}, config={"recursion_limit": 20})
        if result.get("messages"):
            final = message_text(result["messages"][-1])
        else:
            final = str(result)
        return {"final_answer": final, "messages": [AIMessage(content=final)]}

    def _knowledge_node(state: DataAgentState) -> dict:
        """Invoke the Knowledge Search sub-agent."""
        message = state.messages[-1].content if state.messages else ""
        knowledge_input = KnowledgeAgentState(messages=[HumanMessage(content=message)])
        result = knowledge_agent.invoke({"messages": state.messages}, config={"recursion_limit": 20})
        if result.get("messages"):
            final = message_text(result["messages"][-1])
        else:
            final = str(result)
        return {"final_answer": final, "messages": [AIMessage(content=final)]}

    def _router_edge(state: DataAgentState) -> str:
        route = state.route.upper()
        if route == "ETL":
            return "etl_node"
        elif route == "KNOWLEDGE":
            return "knowledge_node"
        return "sql_node"

    graph = StateGraph(DataAgentState)
    graph.add_node("router_node", RunnableLambda(_router_node))
    graph.add_node("sql_node", RunnableLambda(_sql_node))
    graph.add_node("etl_node", RunnableLambda(_etl_node))
    graph.add_node("knowledge_node", RunnableLambda(_knowledge_node))

    graph.add_edge(START, "router_node")
    graph.add_conditional_edges("router_node", _router_edge,
        {"sql_node": "sql_node", "etl_node": "etl_node", "knowledge_node": "knowledge_node"})
    graph.add_edge("sql_node", END)
    graph.add_edge("etl_node", END)
    graph.add_edge("knowledge_node", END)

    return graph.compile()


# ════════════════════════════════════════════════════════════════
# RESPONSES AGENT — MLflow Model Serving wrapper
# This is the interface that Model Serving calls when the endpoint
# receives a request from the Databricks App or external clients.
# ════════════════════════════════════════════════════════════════

class DataAgent(ResponsesAgent):
    """Multi-Agent Data Agent deployed via MLflow Model Serving.

    Wraps the LangGraph multi-agent system in the ResponsesAgent interface
    so it can be deployed as a Model Serving endpoint and called from
    the Databricks App (browser UI).
    """

    def __init__(self):
        self.graph = None

    def predict(self, request: ResponsesAgentRequest) -> ResponsesAgentResponse:
        """Non-streaming prediction — routes user query through the full agent graph."""
        outputs = [
            event.item
            for event in self.predict_stream(request)
            if event.type == "response.output_item.done"
        ]
        return ResponsesAgentResponse(output=outputs)

    def predict_stream(
        self, request: ResponsesAgentRequest
    ) -> Generator[ResponsesAgentStreamEvent, None, None]:
        """Streaming prediction — streams agent responses as they are generated."""
        try:
            raw_messages = to_chat_completions_input([m.model_dump() for m in request.input])

            # Convert dict messages to LangChain message objects
            lc_messages = []
            for m in raw_messages:
                if isinstance(m, dict):
                    role = m.get("role", "user")
                    content = m.get("content", "")
                    if role == "assistant":
                        lc_messages.append(AIMessage(content=content))
                    else:
                        lc_messages.append(HumanMessage(content=content))
                else:
                    lc_messages.append(m)

            # Run the full multi-agent graph
            if self.graph is None:
                self.graph = _build_data_agent_graph()
            result = self.graph.invoke({"messages": lc_messages})

            # Extract the final answer
            final_answer = result.get("final_answer", "")
            if not final_answer and result.get("messages"):
                last_msg = result["messages"][-1]
                final_answer = message_text(last_msg) if hasattr(last_msg, 'content') else str(last_msg)
        except Exception as e:
            logger.exception("Agent execution failed")
            raise

        # Yield as a text output item
        yield ResponsesAgentStreamEvent(
            type="response.output_item.done",
            item=self.create_text_output_item(text=final_answer, id="msg_final"),
        )


# ════════════════════════════════════════════════════════════════
# MLFLOW EXPORT — Required for Model Serving deployment
# ════════════════════════════════════════════════════════════════

AGENT = DataAgent()
mlflow.models.set_model(AGENT)
