"""Pydantic schema models for the AI Data Agent."""
from typing import Annotated, Literal
from operator import add
from pydantic import BaseModel, Field


class AgentSchema(BaseModel):
    """State carried through every node of the SQL Analyst stateful graph."""
    messages: Annotated[list, add] = Field(default_factory=list, description="Chat messages processed by the SQL agent")
    user_question: str = Field(default="", description="Raw user input question")
    curated_question: str = Field(default="", description="Curated/refined user question")
    prompt_query_context: str = Field(default="", description="Detailed prompt with SQL DB context for query generation")
    is_safe: Literal["yes", "no"] = Field(default="no", description="Whether the generated SQL is safe to execute")
    comments: str = Field(default="", description="Judge comments or feedback on the SQL query")
    generated_sql_query: str = Field(default="", description="SQL query generated by the LLM")
    sql_query_execution_result: str = Field(default="", description="Result after executing the SQL query")
    final_answer: str = Field(default="", description="Final user-facing answer")


class JudgeSchema(BaseModel):
    """Structured output schema for the AI-as-judge SQL safety check."""
    answer: Literal["yes", "no"] = Field(description="Whether the SQL query is safe to execute")
    comments: str = Field(default="", description="Additional comments or feedback from the judge")


class RouterSchema(BaseModel):
    """Structured output schema for the parent router decision."""
    answer: Literal["SQL", "ETL"] = Field(description="Whether the user's question is related to SQL data retrieval or ETL operations")
    comments: str = Field(default="", description="Brief justification for the routing decision")


class ETLAgentSchema(BaseModel):
    """State carried through the ETL Analyst react agent graph."""
    messages: Annotated[list, add] = Field(default_factory=list, description="Chat messages processed by the ETL agent")


class DataAgentSchema(BaseModel):
    """State carried through the parent Data Agent graph."""
    messages: Annotated[list, add] = Field(default_factory=list, description="Chat messages for the parent agent")
    route_response: str = Field(default="", description="Routing decision: 'SQL' or 'ETL'")
    final_answer: str = Field(default="", description="Final user-facing answer")
